name: Scrape Email

on:
  push:
    branches:
      - main  
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}  # Add workflow dispatch for manual triggering

jobs:
  Scrape-Email:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scrapper
        run: |
          # Pass the secrests as environment variables to script
          python email_scrapper.py          

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "::set-output name=changes::true"

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git pull
          git add .
          git commit -m "Updated leaderboard and resized images for Project 1."
          git remote set-url origin https://$API_TOKEN@github.com/mlsanigeria/AI-Hacktober-MLSA.git
          git push
